version: '3.4'

services:
  # hotelmanagementsystem.identityserver:
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #     - ASPNETCORE_HTTP_PORTS=5001
  #     - ASPNETCORE_HTTPS_PORTS=5002
  #   ports:
  #     - "5001:5001"
  #     - "5002:5002"

  hotelmanagementsystem.frontdesk.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5005
    expose:
      - "5005"
    ports:
      - "5005:5005"

  hotelmanagementsystem.admin.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5003
    expose:
      - "5003"
    ports:
      - "5003:80"