// <auto-generated />
using System;
using HotelManagementSystem.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HotelManagementSystem.Admin.DataAccess.Migrations
{
    [DbContext(typeof(AdminDbContext))]
    [Migration("20240417165212_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("HotelManagementSystem.Contracts.Entities.Admin.HotelBranch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("IsCurrent")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.HasKey("Id");

                    b.ToTable("Branches");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Dublin 01",
                            City = "Dublin",
                            IsActive = true,
                            IsCurrent = 1,
                            Name = "The Wangchuks Hotel, Dublin"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Cork 01",
                            City = "Cork",
                            IsActive = true,
                            IsCurrent = 0,
                            Name = "The Wangchuks Hotel, Cork"
                        });
                });

            modelBuilder.Entity("HotelManagementSystem.Contracts.Entities.Admin.Permission", b =>
                {
                    b.Property<int>("PermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<int>("HotelBranchId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("PermissionId");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            PermissionId = 1,
                            CreatedAt = new DateTime(2024, 4, 17, 16, 52, 11, 281, DateTimeKind.Utc).AddTicks(9725),
                            Description = "Permission to add a new role to a branch",
                            HotelBranchId = 1,
                            Name = "admin:role:add"
                        },
                        new
                        {
                            PermissionId = 2,
                            CreatedAt = new DateTime(2024, 4, 17, 16, 52, 11, 281, DateTimeKind.Utc).AddTicks(9730),
                            Description = "Permission to view a role",
                            HotelBranchId = 1,
                            Name = "admin:role:view"
                        },
                        new
                        {
                            PermissionId = 3,
                            CreatedAt = new DateTime(2024, 4, 17, 16, 52, 11, 281, DateTimeKind.Utc).AddTicks(9732),
                            Description = "Permission to edit a role",
                            HotelBranchId = 1,
                            Name = "admin:role:edit"
                        },
                        new
                        {
                            PermissionId = 4,
                            CreatedAt = new DateTime(2024, 4, 17, 16, 52, 11, 281, DateTimeKind.Utc).AddTicks(9735),
                            Description = "Permission to delete a role",
                            HotelBranchId = 1,
                            Name = "admin:role:delete"
                        },
                        new
                        {
                            PermissionId = 5,
                            CreatedAt = new DateTime(2024, 4, 17, 16, 52, 11, 281, DateTimeKind.Utc).AddTicks(9737),
                            Description = "Permission to add a permission",
                            HotelBranchId = 1,
                            Name = "admin:permission:add"
                        },
                        new
                        {
                            PermissionId = 6,
                            CreatedAt = new DateTime(2024, 4, 17, 16, 52, 11, 281, DateTimeKind.Utc).AddTicks(9741),
                            Description = "Permission to view a permission",
                            HotelBranchId = 1,
                            Name = "admin:permission:view"
                        },
                        new
                        {
                            PermissionId = 7,
                            CreatedAt = new DateTime(2024, 4, 17, 16, 52, 11, 281, DateTimeKind.Utc).AddTicks(9743),
                            Description = "Permission to edit a permission",
                            HotelBranchId = 1,
                            Name = "admin:permission:edit"
                        },
                        new
                        {
                            PermissionId = 8,
                            CreatedAt = new DateTime(2024, 4, 17, 16, 52, 11, 281, DateTimeKind.Utc).AddTicks(9745),
                            Description = "Permission to delete a permission",
                            HotelBranchId = 1,
                            Name = "admin:permission:delete"
                        },
                        new
                        {
                            PermissionId = 9,
                            CreatedAt = new DateTime(2024, 4, 17, 16, 52, 11, 281, DateTimeKind.Utc).AddTicks(9747),
                            Description = "Permission to add a user",
                            HotelBranchId = 1,
                            Name = "admin:user:add"
                        },
                        new
                        {
                            PermissionId = 10,
                            CreatedAt = new DateTime(2024, 4, 17, 16, 52, 11, 281, DateTimeKind.Utc).AddTicks(9750),
                            Description = "Permission to view a user",
                            HotelBranchId = 1,
                            Name = "admin:user:view"
                        },
                        new
                        {
                            PermissionId = 11,
                            CreatedAt = new DateTime(2024, 4, 17, 16, 52, 11, 281, DateTimeKind.Utc).AddTicks(9754),
                            Description = "Permission to add a user",
                            HotelBranchId = 1,
                            Name = "admin:user:edit"
                        },
                        new
                        {
                            PermissionId = 12,
                            CreatedAt = new DateTime(2024, 4, 17, 16, 52, 11, 281, DateTimeKind.Utc).AddTicks(9756),
                            Description = "Permission to add a user",
                            HotelBranchId = 1,
                            Name = "admin:user:delete"
                        },
                        new
                        {
                            PermissionId = 13,
                            CreatedAt = new DateTime(2024, 4, 17, 16, 52, 11, 281, DateTimeKind.Utc).AddTicks(9758),
                            Description = "Permission to add a visitor",
                            HotelBranchId = 1,
                            Name = "admin:visitor:add"
                        },
                        new
                        {
                            PermissionId = 14,
                            CreatedAt = new DateTime(2024, 4, 17, 16, 52, 11, 281, DateTimeKind.Utc).AddTicks(9760),
                            Description = "Permission to view a visitor",
                            HotelBranchId = 1,
                            Name = "admin:visitor:view"
                        },
                        new
                        {
                            PermissionId = 15,
                            CreatedAt = new DateTime(2024, 4, 17, 16, 52, 11, 281, DateTimeKind.Utc).AddTicks(9762),
                            Description = "Permission to edit a visitor",
                            HotelBranchId = 1,
                            Name = "admin:visitor:edit"
                        },
                        new
                        {
                            PermissionId = 16,
                            CreatedAt = new DateTime(2024, 4, 17, 16, 52, 11, 281, DateTimeKind.Utc).AddTicks(9764),
                            Description = "Permission to delete a visitor",
                            HotelBranchId = 1,
                            Name = "admin:visitor:delete"
                        },
                        new
                        {
                            PermissionId = 17,
                            CreatedAt = new DateTime(2024, 4, 17, 16, 52, 11, 281, DateTimeKind.Utc).AddTicks(9766),
                            Description = "All Permissions",
                            HotelBranchId = 1,
                            Name = "superadmin"
                        },
                        new
                        {
                            PermissionId = 18,
                            CreatedAt = new DateTime(2024, 4, 17, 16, 52, 11, 281, DateTimeKind.Utc).AddTicks(9770),
                            Description = "Permission to add a visitor booking",
                            HotelBranchId = 1,
                            Name = "frontdesk:booking:add"
                        },
                        new
                        {
                            PermissionId = 19,
                            CreatedAt = new DateTime(2024, 4, 17, 16, 52, 11, 281, DateTimeKind.Utc).AddTicks(9772),
                            Description = "Permission to view a visitor booking",
                            HotelBranchId = 1,
                            Name = "frontdesk:booking:view"
                        },
                        new
                        {
                            PermissionId = 20,
                            CreatedAt = new DateTime(2024, 4, 17, 16, 52, 11, 281, DateTimeKind.Utc).AddTicks(9774),
                            Description = "Permission to edit a visitor booking",
                            HotelBranchId = 1,
                            Name = "frontdesk:booking:edit"
                        },
                        new
                        {
                            PermissionId = 21,
                            CreatedAt = new DateTime(2024, 4, 17, 16, 52, 11, 281, DateTimeKind.Utc).AddTicks(9776),
                            Description = "Permission to delete a visitor booking",
                            HotelBranchId = 1,
                            Name = "frontdesk:booking:delete"
                        },
                        new
                        {
                            PermissionId = 22,
                            CreatedAt = new DateTime(2024, 4, 17, 16, 52, 11, 281, DateTimeKind.Utc).AddTicks(9777),
                            Description = "Permission to approve a visitor booking",
                            HotelBranchId = 1,
                            Name = "frontdesk:booking:approve"
                        },
                        new
                        {
                            PermissionId = 23,
                            CreatedAt = new DateTime(2024, 4, 17, 16, 52, 11, 281, DateTimeKind.Utc).AddTicks(9779),
                            Description = "Permission to decline a visitor booking",
                            HotelBranchId = 1,
                            Name = "frontdesk:booking:decline"
                        },
                        new
                        {
                            PermissionId = 24,
                            CreatedAt = new DateTime(2024, 4, 17, 16, 52, 11, 281, DateTimeKind.Utc).AddTicks(9781),
                            Description = "Permission to add a visitor",
                            HotelBranchId = 1,
                            Name = "frontdesk:visior:add"
                        },
                        new
                        {
                            PermissionId = 25,
                            CreatedAt = new DateTime(2024, 4, 17, 16, 52, 11, 281, DateTimeKind.Utc).AddTicks(9783),
                            Description = "Permission to view a visitor",
                            HotelBranchId = 1,
                            Name = "frontdesk:visior:view"
                        },
                        new
                        {
                            PermissionId = 26,
                            CreatedAt = new DateTime(2024, 4, 17, 16, 52, 11, 281, DateTimeKind.Utc).AddTicks(9785),
                            Description = "Permission to edit a visitor",
                            HotelBranchId = 1,
                            Name = "frontdesk:visior:edit"
                        },
                        new
                        {
                            PermissionId = 27,
                            CreatedAt = new DateTime(2024, 4, 17, 16, 52, 11, 281, DateTimeKind.Utc).AddTicks(9787),
                            Description = "Permission to delete a visitor",
                            HotelBranchId = 1,
                            Name = "frontdesk:visior:delete"
                        });
                });

            modelBuilder.Entity("HotelManagementSystem.Contracts.Entities.Admin.PermissionAssignment", b =>
                {
                    b.Property<int>("PermissionAssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("longtext");

                    b.Property<int>("HotelBranchId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("PermissionAssignmentId");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId");

                    b.ToTable("PermissionAssignments");

                    b.HasData(
                        new
                        {
                            PermissionAssignmentId = 1,
                            CreatedAt = new DateTime(2024, 4, 17, 16, 52, 11, 281, DateTimeKind.Utc).AddTicks(9996),
                            CreatedBy = "System",
                            HotelBranchId = 1,
                            IsDeleted = false,
                            PermissionId = 17,
                            RoleId = 1
                        },
                        new
                        {
                            PermissionAssignmentId = 2,
                            CreatedAt = new DateTime(2024, 4, 17, 16, 52, 11, 282, DateTimeKind.Utc).AddTicks(1),
                            CreatedBy = "System",
                            HotelBranchId = 1,
                            IsDeleted = false,
                            PermissionId = 1,
                            RoleId = 2
                        },
                        new
                        {
                            PermissionAssignmentId = 3,
                            CreatedAt = new DateTime(2024, 4, 17, 16, 52, 11, 282, DateTimeKind.Utc).AddTicks(4),
                            CreatedBy = "System",
                            HotelBranchId = 1,
                            IsDeleted = false,
                            PermissionId = 2,
                            RoleId = 2
                        },
                        new
                        {
                            PermissionAssignmentId = 4,
                            CreatedAt = new DateTime(2024, 4, 17, 16, 52, 11, 282, DateTimeKind.Utc).AddTicks(6),
                            CreatedBy = "System",
                            HotelBranchId = 1,
                            IsDeleted = false,
                            PermissionId = 3,
                            RoleId = 2
                        },
                        new
                        {
                            PermissionAssignmentId = 5,
                            CreatedAt = new DateTime(2024, 4, 17, 16, 52, 11, 282, DateTimeKind.Utc).AddTicks(8),
                            CreatedBy = "System",
                            HotelBranchId = 1,
                            IsDeleted = false,
                            PermissionId = 4,
                            RoleId = 2
                        },
                        new
                        {
                            PermissionAssignmentId = 6,
                            CreatedAt = new DateTime(2024, 4, 17, 16, 52, 11, 282, DateTimeKind.Utc).AddTicks(11),
                            CreatedBy = "System",
                            HotelBranchId = 1,
                            IsDeleted = false,
                            PermissionId = 5,
                            RoleId = 2
                        },
                        new
                        {
                            PermissionAssignmentId = 7,
                            CreatedAt = new DateTime(2024, 4, 17, 16, 52, 11, 282, DateTimeKind.Utc).AddTicks(13),
                            CreatedBy = "System",
                            HotelBranchId = 1,
                            IsDeleted = false,
                            PermissionId = 6,
                            RoleId = 2
                        },
                        new
                        {
                            PermissionAssignmentId = 8,
                            CreatedAt = new DateTime(2024, 4, 17, 16, 52, 11, 282, DateTimeKind.Utc).AddTicks(15),
                            CreatedBy = "System",
                            HotelBranchId = 1,
                            IsDeleted = false,
                            PermissionId = 7,
                            RoleId = 2
                        },
                        new
                        {
                            PermissionAssignmentId = 9,
                            CreatedAt = new DateTime(2024, 4, 17, 16, 52, 11, 282, DateTimeKind.Utc).AddTicks(17),
                            CreatedBy = "System",
                            HotelBranchId = 1,
                            IsDeleted = false,
                            PermissionId = 8,
                            RoleId = 2
                        },
                        new
                        {
                            PermissionAssignmentId = 10,
                            CreatedAt = new DateTime(2024, 4, 17, 16, 52, 11, 282, DateTimeKind.Utc).AddTicks(20),
                            CreatedBy = "System",
                            HotelBranchId = 1,
                            IsDeleted = false,
                            PermissionId = 8,
                            RoleId = 2
                        },
                        new
                        {
                            PermissionAssignmentId = 11,
                            CreatedAt = new DateTime(2024, 4, 17, 16, 52, 11, 282, DateTimeKind.Utc).AddTicks(22),
                            CreatedBy = "System",
                            HotelBranchId = 1,
                            IsDeleted = false,
                            PermissionId = 9,
                            RoleId = 2
                        },
                        new
                        {
                            PermissionAssignmentId = 12,
                            CreatedAt = new DateTime(2024, 4, 17, 16, 52, 11, 282, DateTimeKind.Utc).AddTicks(24),
                            CreatedBy = "System",
                            HotelBranchId = 1,
                            IsDeleted = false,
                            PermissionId = 10,
                            RoleId = 2
                        },
                        new
                        {
                            PermissionAssignmentId = 13,
                            CreatedAt = new DateTime(2024, 4, 17, 16, 52, 11, 282, DateTimeKind.Utc).AddTicks(26),
                            CreatedBy = "System",
                            HotelBranchId = 1,
                            IsDeleted = false,
                            PermissionId = 11,
                            RoleId = 2
                        },
                        new
                        {
                            PermissionAssignmentId = 14,
                            CreatedAt = new DateTime(2024, 4, 17, 16, 52, 11, 282, DateTimeKind.Utc).AddTicks(28),
                            CreatedBy = "System",
                            HotelBranchId = 1,
                            IsDeleted = false,
                            PermissionId = 12,
                            RoleId = 2
                        },
                        new
                        {
                            PermissionAssignmentId = 15,
                            CreatedAt = new DateTime(2024, 4, 17, 16, 52, 11, 282, DateTimeKind.Utc).AddTicks(30),
                            CreatedBy = "System",
                            HotelBranchId = 1,
                            IsDeleted = false,
                            PermissionId = 13,
                            RoleId = 2
                        },
                        new
                        {
                            PermissionAssignmentId = 16,
                            CreatedAt = new DateTime(2024, 4, 17, 16, 52, 11, 282, DateTimeKind.Utc).AddTicks(32),
                            CreatedBy = "System",
                            HotelBranchId = 1,
                            IsDeleted = false,
                            PermissionId = 14,
                            RoleId = 2
                        },
                        new
                        {
                            PermissionAssignmentId = 17,
                            CreatedAt = new DateTime(2024, 4, 17, 16, 52, 11, 282, DateTimeKind.Utc).AddTicks(35),
                            CreatedBy = "System",
                            HotelBranchId = 1,
                            IsDeleted = false,
                            PermissionId = 15,
                            RoleId = 2
                        },
                        new
                        {
                            PermissionAssignmentId = 18,
                            CreatedAt = new DateTime(2024, 4, 17, 16, 52, 11, 282, DateTimeKind.Utc).AddTicks(38),
                            CreatedBy = "System",
                            HotelBranchId = 1,
                            IsDeleted = false,
                            PermissionId = 16,
                            RoleId = 2
                        },
                        new
                        {
                            PermissionAssignmentId = 32,
                            CreatedAt = new DateTime(2024, 4, 17, 16, 52, 11, 282, DateTimeKind.Utc).AddTicks(41),
                            CreatedBy = "System",
                            HotelBranchId = 1,
                            IsDeleted = false,
                            PermissionId = 18,
                            RoleId = 3
                        },
                        new
                        {
                            PermissionAssignmentId = 19,
                            CreatedAt = new DateTime(2024, 4, 17, 16, 52, 11, 282, DateTimeKind.Utc).AddTicks(43),
                            CreatedBy = "System",
                            HotelBranchId = 1,
                            IsDeleted = false,
                            PermissionId = 19,
                            RoleId = 3
                        },
                        new
                        {
                            PermissionAssignmentId = 20,
                            CreatedAt = new DateTime(2024, 4, 17, 16, 52, 11, 282, DateTimeKind.Utc).AddTicks(45),
                            CreatedBy = "System",
                            HotelBranchId = 1,
                            IsDeleted = false,
                            PermissionId = 20,
                            RoleId = 3
                        },
                        new
                        {
                            PermissionAssignmentId = 21,
                            CreatedAt = new DateTime(2024, 4, 17, 16, 52, 11, 282, DateTimeKind.Utc).AddTicks(47),
                            CreatedBy = "System",
                            HotelBranchId = 1,
                            IsDeleted = false,
                            PermissionId = 21,
                            RoleId = 3
                        },
                        new
                        {
                            PermissionAssignmentId = 22,
                            CreatedAt = new DateTime(2024, 4, 17, 16, 52, 11, 282, DateTimeKind.Utc).AddTicks(48),
                            CreatedBy = "System",
                            HotelBranchId = 1,
                            IsDeleted = false,
                            PermissionId = 22,
                            RoleId = 3
                        },
                        new
                        {
                            PermissionAssignmentId = 23,
                            CreatedAt = new DateTime(2024, 4, 17, 16, 52, 11, 282, DateTimeKind.Utc).AddTicks(50),
                            CreatedBy = "System",
                            HotelBranchId = 1,
                            IsDeleted = false,
                            PermissionId = 23,
                            RoleId = 3
                        },
                        new
                        {
                            PermissionAssignmentId = 24,
                            CreatedAt = new DateTime(2024, 4, 17, 16, 52, 11, 282, DateTimeKind.Utc).AddTicks(52),
                            CreatedBy = "System",
                            HotelBranchId = 1,
                            IsDeleted = false,
                            PermissionId = 24,
                            RoleId = 3
                        },
                        new
                        {
                            PermissionAssignmentId = 25,
                            CreatedAt = new DateTime(2024, 4, 17, 16, 52, 11, 282, DateTimeKind.Utc).AddTicks(54),
                            CreatedBy = "System",
                            HotelBranchId = 1,
                            IsDeleted = false,
                            PermissionId = 25,
                            RoleId = 3
                        },
                        new
                        {
                            PermissionAssignmentId = 26,
                            CreatedAt = new DateTime(2024, 4, 17, 16, 52, 11, 282, DateTimeKind.Utc).AddTicks(56),
                            CreatedBy = "System",
                            HotelBranchId = 1,
                            IsDeleted = false,
                            PermissionId = 18,
                            RoleId = 4
                        },
                        new
                        {
                            PermissionAssignmentId = 27,
                            CreatedAt = new DateTime(2024, 4, 17, 16, 52, 11, 282, DateTimeKind.Utc).AddTicks(58),
                            CreatedBy = "System",
                            HotelBranchId = 1,
                            IsDeleted = false,
                            PermissionId = 19,
                            RoleId = 4
                        },
                        new
                        {
                            PermissionAssignmentId = 28,
                            CreatedAt = new DateTime(2024, 4, 17, 16, 52, 11, 282, DateTimeKind.Utc).AddTicks(60),
                            CreatedBy = "System",
                            HotelBranchId = 1,
                            IsDeleted = false,
                            PermissionId = 20,
                            RoleId = 4
                        },
                        new
                        {
                            PermissionAssignmentId = 29,
                            CreatedAt = new DateTime(2024, 4, 17, 16, 52, 11, 282, DateTimeKind.Utc).AddTicks(62),
                            CreatedBy = "System",
                            HotelBranchId = 1,
                            IsDeleted = false,
                            PermissionId = 22,
                            RoleId = 4
                        },
                        new
                        {
                            PermissionAssignmentId = 30,
                            CreatedAt = new DateTime(2024, 4, 17, 16, 52, 11, 282, DateTimeKind.Utc).AddTicks(68),
                            CreatedBy = "System",
                            HotelBranchId = 1,
                            IsDeleted = false,
                            PermissionId = 24,
                            RoleId = 4
                        },
                        new
                        {
                            PermissionAssignmentId = 31,
                            CreatedAt = new DateTime(2024, 4, 17, 16, 52, 11, 282, DateTimeKind.Utc).AddTicks(70),
                            CreatedBy = "System",
                            HotelBranchId = 1,
                            IsDeleted = false,
                            PermissionId = 25,
                            RoleId = 4
                        });
                });

            modelBuilder.Entity("HotelManagementSystem.Contracts.Entities.Admin.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<int>("HotelBranchId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            CreatedAt = new DateTime(2024, 4, 17, 16, 52, 11, 281, DateTimeKind.Utc).AddTicks(9658),
                            CreatedBy = "System",
                            Description = "Has all the Permissions",
                            HotelBranchId = 1,
                            IsDeleted = false,
                            Name = "Super Admin",
                            ShortName = "SuperAdmin"
                        },
                        new
                        {
                            RoleId = 2,
                            CreatedAt = new DateTime(2024, 4, 17, 16, 52, 11, 281, DateTimeKind.Utc).AddTicks(9668),
                            CreatedBy = "System",
                            Description = "Has all the root permissions",
                            HotelBranchId = 1,
                            IsDeleted = false,
                            Name = "Admin",
                            ShortName = "Admin"
                        },
                        new
                        {
                            RoleId = 3,
                            CreatedAt = new DateTime(2024, 4, 17, 16, 52, 11, 281, DateTimeKind.Utc).AddTicks(9671),
                            CreatedBy = "System",
                            Description = "Manager of the Front Desk Department",
                            HotelBranchId = 1,
                            IsDeleted = false,
                            Name = "Front Desk Manager",
                            ShortName = "FDManager"
                        },
                        new
                        {
                            RoleId = 4,
                            CreatedAt = new DateTime(2024, 4, 17, 16, 52, 11, 281, DateTimeKind.Utc).AddTicks(9677),
                            CreatedBy = "System",
                            Description = "Assistant staff of the Front Desk Department",
                            HotelBranchId = 1,
                            IsDeleted = false,
                            Name = "Front Desk Assistant",
                            ShortName = "FDAssistant"
                        });
                });

            modelBuilder.Entity("HotelManagementSystem.Contracts.Entities.Admin.RoleAssignment", b =>
                {
                    b.Property<int>("RoleAssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ExpiredAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("HotelBranchId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("RoleAssignmentId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("RoleAssignments");

                    b.HasData(
                        new
                        {
                            RoleAssignmentId = 1,
                            CreatedAt = new DateTime(2024, 4, 17, 16, 52, 11, 282, DateTimeKind.Utc).AddTicks(471),
                            CreatedBy = "System",
                            HotelBranchId = 1,
                            IsDeleted = false,
                            RoleId = 1,
                            UserId = 5
                        },
                        new
                        {
                            RoleAssignmentId = 2,
                            CreatedAt = new DateTime(2024, 4, 17, 16, 52, 11, 282, DateTimeKind.Utc).AddTicks(476),
                            CreatedBy = "System",
                            HotelBranchId = 1,
                            IsDeleted = false,
                            RoleId = 3,
                            UserId = 1
                        },
                        new
                        {
                            RoleAssignmentId = 3,
                            CreatedAt = new DateTime(2024, 4, 17, 16, 52, 11, 282, DateTimeKind.Utc).AddTicks(479),
                            CreatedBy = "System",
                            HotelBranchId = 1,
                            IsDeleted = false,
                            RoleId = 4,
                            UserId = 2
                        },
                        new
                        {
                            RoleAssignmentId = 4,
                            CreatedAt = new DateTime(2024, 4, 17, 16, 52, 11, 282, DateTimeKind.Utc).AddTicks(481),
                            CreatedBy = "System",
                            HotelBranchId = 1,
                            IsDeleted = false,
                            RoleId = 4,
                            UserId = 3
                        },
                        new
                        {
                            RoleAssignmentId = 5,
                            CreatedAt = new DateTime(2024, 4, 17, 16, 52, 11, 282, DateTimeKind.Utc).AddTicks(483),
                            CreatedBy = "System",
                            HotelBranchId = 1,
                            IsDeleted = false,
                            RoleId = 3,
                            UserId = 4
                        });
                });

            modelBuilder.Entity("HotelManagementSystem.Contracts.Entities.Admin.Roster", b =>
                {
                    b.Property<int>("RosterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ShiftId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("RosterId");

                    b.HasIndex("ShiftId");

                    b.HasIndex("UserId");

                    b.ToTable("Roster");
                });

            modelBuilder.Entity("HotelManagementSystem.Contracts.Entities.Admin.Shift", b =>
                {
                    b.Property<int>("ShiftId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ShiftName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ShiftId");

                    b.ToTable("Shift");
                });

            modelBuilder.Entity("HotelManagementSystem.Contracts.Entities.Admin.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AddressLine1")
                        .HasColumnType("longtext");

                    b.Property<string>("AddressLine2")
                        .HasColumnType("longtext");

                    b.Property<string>("City")
                        .HasColumnType("longtext");

                    b.Property<string>("Country")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("ExpiredAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Gender")
                        .HasColumnType("longtext");

                    b.Property<Guid>("Guid")
                        .HasColumnType("char(36)");

                    b.Property<int>("HotelBranchId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsExpired")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("State")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Zipcode")
                        .HasColumnType("longtext");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Phone")
                        .IsUnique();

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            CreatedAt = new DateTime(2024, 4, 17, 16, 52, 11, 282, DateTimeKind.Utc).AddTicks(297),
                            CreatedBy = "System",
                            Email = "namblyakshay@gmail.com",
                            FirstName = "Akshay",
                            Guid = new Guid("1cfc398c-325a-4749-b95a-4bf5dbc0c141"),
                            HotelBranchId = 1,
                            IsActive = true,
                            IsDeleted = false,
                            IsEmailVerified = true,
                            IsExpired = false,
                            LastName = "Nambly",
                            MiddleName = "Mohanan",
                            Password = "Test1234",
                            Phone = "12345",
                            UserName = "akshayn"
                        },
                        new
                        {
                            UserId = 2,
                            CreatedAt = new DateTime(2024, 4, 17, 16, 52, 11, 282, DateTimeKind.Utc).AddTicks(313),
                            CreatedBy = "System",
                            Email = "chaitraumesh.96@gmail.com",
                            FirstName = "Chaitra",
                            Guid = new Guid("8ae5da68-2812-4853-9a24-9660ff424f44"),
                            HotelBranchId = 1,
                            IsActive = true,
                            IsDeleted = false,
                            IsEmailVerified = true,
                            IsExpired = false,
                            LastName = "Umesh",
                            MiddleName = "",
                            Password = "Test1234",
                            Phone = "123456",
                            UserName = "chaitrau"
                        },
                        new
                        {
                            UserId = 3,
                            CreatedAt = new DateTime(2024, 4, 17, 16, 52, 11, 282, DateTimeKind.Utc).AddTicks(319),
                            CreatedBy = "System",
                            Email = "jittythomas774@gmail.com",
                            FirstName = "Jitty",
                            Guid = new Guid("988f6586-50d3-4f12-b7b7-eb99e5873d2c"),
                            HotelBranchId = 1,
                            IsActive = true,
                            IsDeleted = false,
                            IsEmailVerified = true,
                            IsExpired = false,
                            LastName = "Thomas",
                            MiddleName = "",
                            Password = "Test1234",
                            Phone = "123457",
                            UserName = "jittyt"
                        },
                        new
                        {
                            UserId = 4,
                            CreatedAt = new DateTime(2024, 4, 17, 16, 52, 11, 282, DateTimeKind.Utc).AddTicks(325),
                            CreatedBy = "System",
                            Email = "robinssojan26@gmail.com",
                            FirstName = "Robins",
                            Guid = new Guid("e9d70881-5ec6-4c40-99e1-a3eb6304a2a9"),
                            HotelBranchId = 1,
                            IsActive = true,
                            IsDeleted = false,
                            IsEmailVerified = true,
                            IsExpired = false,
                            LastName = "Sojan",
                            MiddleName = "",
                            Password = "Test1234",
                            Phone = "123458",
                            UserName = "robinss"
                        },
                        new
                        {
                            UserId = 5,
                            CreatedAt = new DateTime(2024, 4, 17, 16, 52, 11, 282, DateTimeKind.Utc).AddTicks(330),
                            CreatedBy = "System",
                            Email = "test.admin@gmail.com",
                            FirstName = "Super",
                            Guid = new Guid("1f92d770-64bd-483a-9422-f81581e4deb0"),
                            HotelBranchId = 1,
                            IsActive = true,
                            IsDeleted = false,
                            IsEmailVerified = true,
                            IsExpired = false,
                            LastName = "Admin",
                            MiddleName = "",
                            Password = "Test1234",
                            Phone = "123459",
                            UserName = "superAdmin"
                        });
                });

            modelBuilder.Entity("HotelManagementSystem.Contracts.Entities.Admin.UserPasswordResets", b =>
                {
                    b.Property<int>("UserPasswordResetsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ExpiresOn")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsEmailSent")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PasswordResetToken")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("UserPasswordResetsId");

                    b.HasIndex("UserId");

                    b.ToTable("UserPasswordResets");
                });

            modelBuilder.Entity("HotelManagementSystem.Contracts.Entities.Admin.PermissionAssignment", b =>
                {
                    b.HasOne("HotelManagementSystem.Contracts.Entities.Admin.Permission", "Permission")
                        .WithMany("PermissionAssignments")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HotelManagementSystem.Contracts.Entities.Admin.Role", "Role")
                        .WithMany("PermissionAssignments")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("HotelManagementSystem.Contracts.Entities.Admin.RoleAssignment", b =>
                {
                    b.HasOne("HotelManagementSystem.Contracts.Entities.Admin.Role", "Role")
                        .WithMany("RoleAssignments")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HotelManagementSystem.Contracts.Entities.Admin.User", "User")
                        .WithMany("RoleAssignments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HotelManagementSystem.Contracts.Entities.Admin.Roster", b =>
                {
                    b.HasOne("HotelManagementSystem.Contracts.Entities.Admin.Shift", "Shift")
                        .WithMany()
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HotelManagementSystem.Contracts.Entities.Admin.User", "User")
                        .WithMany("Rosters")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shift");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HotelManagementSystem.Contracts.Entities.Admin.UserPasswordResets", b =>
                {
                    b.HasOne("HotelManagementSystem.Contracts.Entities.Admin.User", "User")
                        .WithMany("UserPasswordResets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HotelManagementSystem.Contracts.Entities.Admin.Permission", b =>
                {
                    b.Navigation("PermissionAssignments");
                });

            modelBuilder.Entity("HotelManagementSystem.Contracts.Entities.Admin.Role", b =>
                {
                    b.Navigation("PermissionAssignments");

                    b.Navigation("RoleAssignments");
                });

            modelBuilder.Entity("HotelManagementSystem.Contracts.Entities.Admin.User", b =>
                {
                    b.Navigation("RoleAssignments");

                    b.Navigation("Rosters");

                    b.Navigation("UserPasswordResets");
                });
#pragma warning restore 612, 618
        }
    }
}
