// <auto-generated />
using System;
using HotelManagementSystem.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HotelManagementSystem.Admin.DataAccess.Migrations
{
    [DbContext(typeof(AdminDbContext))]
    [Migration("20240414175904_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("HotelManagementSystem.Contracts.Entities.Admin.HotelBranch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("IsCurrent")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.HasKey("Id");

                    b.ToTable("Branches");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Dublin 01",
                            City = "Dublin",
                            IsActive = true,
                            IsCurrent = 1,
                            Name = "The Wangchuks Hotel, Dublin"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Cork 01",
                            City = "Cork",
                            IsActive = true,
                            IsCurrent = 0,
                            Name = "The Wangchuks Hotel, Cork"
                        });
                });

            modelBuilder.Entity("HotelManagementSystem.Contracts.Entities.Admin.Permission", b =>
                {
                    b.Property<int>("PermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<int>("HotelBranchId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("PermissionId");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            PermissionId = 1,
                            CreatedAt = new DateTime(2024, 4, 14, 17, 59, 4, 290, DateTimeKind.Utc).AddTicks(1819),
                            Description = "Permission to add a new role to a branch",
                            HotelBranchId = 1,
                            Name = "admin:role:add"
                        },
                        new
                        {
                            PermissionId = 2,
                            CreatedAt = new DateTime(2024, 4, 14, 17, 59, 4, 290, DateTimeKind.Utc).AddTicks(1824),
                            Description = "Permission to view a role",
                            HotelBranchId = 1,
                            Name = "admin:role:view"
                        },
                        new
                        {
                            PermissionId = 3,
                            CreatedAt = new DateTime(2024, 4, 14, 17, 59, 4, 290, DateTimeKind.Utc).AddTicks(1827),
                            Description = "Permission to edit a role",
                            HotelBranchId = 1,
                            Name = "admin:role:edit"
                        },
                        new
                        {
                            PermissionId = 4,
                            CreatedAt = new DateTime(2024, 4, 14, 17, 59, 4, 290, DateTimeKind.Utc).AddTicks(1829),
                            Description = "Permission to delete a role",
                            HotelBranchId = 1,
                            Name = "admin:role:delete"
                        },
                        new
                        {
                            PermissionId = 5,
                            CreatedAt = new DateTime(2024, 4, 14, 17, 59, 4, 290, DateTimeKind.Utc).AddTicks(1832),
                            Description = "Permission to add a permission",
                            HotelBranchId = 1,
                            Name = "admin:permission:add"
                        },
                        new
                        {
                            PermissionId = 6,
                            CreatedAt = new DateTime(2024, 4, 14, 17, 59, 4, 290, DateTimeKind.Utc).AddTicks(1842),
                            Description = "Permission to view a permission",
                            HotelBranchId = 1,
                            Name = "admin:permission:view"
                        },
                        new
                        {
                            PermissionId = 7,
                            CreatedAt = new DateTime(2024, 4, 14, 17, 59, 4, 290, DateTimeKind.Utc).AddTicks(1845),
                            Description = "Permission to edit a permission",
                            HotelBranchId = 1,
                            Name = "admin:permission:edit"
                        },
                        new
                        {
                            PermissionId = 8,
                            CreatedAt = new DateTime(2024, 4, 14, 17, 59, 4, 290, DateTimeKind.Utc).AddTicks(1847),
                            Description = "Permission to delete a permission",
                            HotelBranchId = 1,
                            Name = "admin:permission:delete"
                        },
                        new
                        {
                            PermissionId = 9,
                            CreatedAt = new DateTime(2024, 4, 14, 17, 59, 4, 290, DateTimeKind.Utc).AddTicks(1849),
                            Description = "Permission to add a user",
                            HotelBranchId = 1,
                            Name = "admin:user:add"
                        },
                        new
                        {
                            PermissionId = 10,
                            CreatedAt = new DateTime(2024, 4, 14, 17, 59, 4, 290, DateTimeKind.Utc).AddTicks(1853),
                            Description = "Permission to view a user",
                            HotelBranchId = 1,
                            Name = "admin:user:view"
                        },
                        new
                        {
                            PermissionId = 11,
                            CreatedAt = new DateTime(2024, 4, 14, 17, 59, 4, 290, DateTimeKind.Utc).AddTicks(1855),
                            Description = "Permission to add a user",
                            HotelBranchId = 1,
                            Name = "admin:user:edit"
                        },
                        new
                        {
                            PermissionId = 12,
                            CreatedAt = new DateTime(2024, 4, 14, 17, 59, 4, 290, DateTimeKind.Utc).AddTicks(1858),
                            Description = "Permission to add a user",
                            HotelBranchId = 1,
                            Name = "admin:user:delete"
                        },
                        new
                        {
                            PermissionId = 13,
                            CreatedAt = new DateTime(2024, 4, 14, 17, 59, 4, 290, DateTimeKind.Utc).AddTicks(1860),
                            Description = "Permission to add a visitor",
                            HotelBranchId = 1,
                            Name = "admin:visitor:add"
                        },
                        new
                        {
                            PermissionId = 14,
                            CreatedAt = new DateTime(2024, 4, 14, 17, 59, 4, 290, DateTimeKind.Utc).AddTicks(1861),
                            Description = "Permission to view a visitor",
                            HotelBranchId = 1,
                            Name = "admin:visitor:view"
                        },
                        new
                        {
                            PermissionId = 15,
                            CreatedAt = new DateTime(2024, 4, 14, 17, 59, 4, 290, DateTimeKind.Utc).AddTicks(1864),
                            Description = "Permission to edit a visitor",
                            HotelBranchId = 1,
                            Name = "admin:visitor:edit"
                        },
                        new
                        {
                            PermissionId = 16,
                            CreatedAt = new DateTime(2024, 4, 14, 17, 59, 4, 290, DateTimeKind.Utc).AddTicks(1866),
                            Description = "Permission to delete a visitor",
                            HotelBranchId = 1,
                            Name = "admin:visitor:delete"
                        },
                        new
                        {
                            PermissionId = 17,
                            CreatedAt = new DateTime(2024, 4, 14, 17, 59, 4, 290, DateTimeKind.Utc).AddTicks(1868),
                            Description = "All Permissions",
                            HotelBranchId = 1,
                            Name = "superadmin"
                        },
                        new
                        {
                            PermissionId = 18,
                            CreatedAt = new DateTime(2024, 4, 14, 17, 59, 4, 290, DateTimeKind.Utc).AddTicks(1872),
                            Description = "Permission to add a visitor booking",
                            HotelBranchId = 1,
                            Name = "frontdesk:booking:add"
                        },
                        new
                        {
                            PermissionId = 19,
                            CreatedAt = new DateTime(2024, 4, 14, 17, 59, 4, 290, DateTimeKind.Utc).AddTicks(1874),
                            Description = "Permission to view a visitor booking",
                            HotelBranchId = 1,
                            Name = "frontdesk:booking:view"
                        },
                        new
                        {
                            PermissionId = 20,
                            CreatedAt = new DateTime(2024, 4, 14, 17, 59, 4, 290, DateTimeKind.Utc).AddTicks(1877),
                            Description = "Permission to edit a visitor booking",
                            HotelBranchId = 1,
                            Name = "frontdesk:booking:edit"
                        },
                        new
                        {
                            PermissionId = 21,
                            CreatedAt = new DateTime(2024, 4, 14, 17, 59, 4, 290, DateTimeKind.Utc).AddTicks(1879),
                            Description = "Permission to delete a visitor booking",
                            HotelBranchId = 1,
                            Name = "frontdesk:booking:delete"
                        },
                        new
                        {
                            PermissionId = 22,
                            CreatedAt = new DateTime(2024, 4, 14, 17, 59, 4, 290, DateTimeKind.Utc).AddTicks(1881),
                            Description = "Permission to approve a visitor booking",
                            HotelBranchId = 1,
                            Name = "frontdesk:booking:approve"
                        },
                        new
                        {
                            PermissionId = 23,
                            CreatedAt = new DateTime(2024, 4, 14, 17, 59, 4, 290, DateTimeKind.Utc).AddTicks(1883),
                            Description = "Permission to decline a visitor booking",
                            HotelBranchId = 1,
                            Name = "frontdesk:booking:decline"
                        },
                        new
                        {
                            PermissionId = 24,
                            CreatedAt = new DateTime(2024, 4, 14, 17, 59, 4, 290, DateTimeKind.Utc).AddTicks(1886),
                            Description = "Permission to add a visitor",
                            HotelBranchId = 1,
                            Name = "frontdesk:visior:add"
                        },
                        new
                        {
                            PermissionId = 25,
                            CreatedAt = new DateTime(2024, 4, 14, 17, 59, 4, 290, DateTimeKind.Utc).AddTicks(1888),
                            Description = "Permission to view a visitor",
                            HotelBranchId = 1,
                            Name = "frontdesk:visior:view"
                        },
                        new
                        {
                            PermissionId = 26,
                            CreatedAt = new DateTime(2024, 4, 14, 17, 59, 4, 290, DateTimeKind.Utc).AddTicks(1890),
                            Description = "Permission to edit a visitor",
                            HotelBranchId = 1,
                            Name = "frontdesk:visior:edit"
                        },
                        new
                        {
                            PermissionId = 27,
                            CreatedAt = new DateTime(2024, 4, 14, 17, 59, 4, 290, DateTimeKind.Utc).AddTicks(1892),
                            Description = "Permission to delete a visitor",
                            HotelBranchId = 1,
                            Name = "frontdesk:visior:delete"
                        });
                });

            modelBuilder.Entity("HotelManagementSystem.Contracts.Entities.Admin.PermissionAssignment", b =>
                {
                    b.Property<int>("PermissionAssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("longtext");

                    b.Property<int>("HotelBranchId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("PermissionAssignmentId");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId");

                    b.ToTable("PermissionAssignments");

                    b.HasData(
                        new
                        {
                            PermissionAssignmentId = 1,
                            CreatedAt = new DateTime(2024, 4, 14, 17, 59, 4, 290, DateTimeKind.Utc).AddTicks(2076),
                            CreatedBy = "System",
                            HotelBranchId = 1,
                            IsDeleted = false,
                            PermissionId = 17,
                            RoleId = 1
                        },
                        new
                        {
                            PermissionAssignmentId = 2,
                            CreatedAt = new DateTime(2024, 4, 14, 17, 59, 4, 290, DateTimeKind.Utc).AddTicks(2081),
                            CreatedBy = "System",
                            HotelBranchId = 1,
                            IsDeleted = false,
                            PermissionId = 1,
                            RoleId = 2
                        },
                        new
                        {
                            PermissionAssignmentId = 3,
                            CreatedAt = new DateTime(2024, 4, 14, 17, 59, 4, 290, DateTimeKind.Utc).AddTicks(2084),
                            CreatedBy = "System",
                            HotelBranchId = 1,
                            IsDeleted = false,
                            PermissionId = 2,
                            RoleId = 2
                        },
                        new
                        {
                            PermissionAssignmentId = 4,
                            CreatedAt = new DateTime(2024, 4, 14, 17, 59, 4, 290, DateTimeKind.Utc).AddTicks(2086),
                            CreatedBy = "System",
                            HotelBranchId = 1,
                            IsDeleted = false,
                            PermissionId = 3,
                            RoleId = 2
                        },
                        new
                        {
                            PermissionAssignmentId = 5,
                            CreatedAt = new DateTime(2024, 4, 14, 17, 59, 4, 290, DateTimeKind.Utc).AddTicks(2089),
                            CreatedBy = "System",
                            HotelBranchId = 1,
                            IsDeleted = false,
                            PermissionId = 4,
                            RoleId = 2
                        },
                        new
                        {
                            PermissionAssignmentId = 6,
                            CreatedAt = new DateTime(2024, 4, 14, 17, 59, 4, 290, DateTimeKind.Utc).AddTicks(2092),
                            CreatedBy = "System",
                            HotelBranchId = 1,
                            IsDeleted = false,
                            PermissionId = 5,
                            RoleId = 2
                        },
                        new
                        {
                            PermissionAssignmentId = 7,
                            CreatedAt = new DateTime(2024, 4, 14, 17, 59, 4, 290, DateTimeKind.Utc).AddTicks(2095),
                            CreatedBy = "System",
                            HotelBranchId = 1,
                            IsDeleted = false,
                            PermissionId = 6,
                            RoleId = 2
                        },
                        new
                        {
                            PermissionAssignmentId = 8,
                            CreatedAt = new DateTime(2024, 4, 14, 17, 59, 4, 290, DateTimeKind.Utc).AddTicks(2097),
                            CreatedBy = "System",
                            HotelBranchId = 1,
                            IsDeleted = false,
                            PermissionId = 7,
                            RoleId = 2
                        },
                        new
                        {
                            PermissionAssignmentId = 9,
                            CreatedAt = new DateTime(2024, 4, 14, 17, 59, 4, 290, DateTimeKind.Utc).AddTicks(2100),
                            CreatedBy = "System",
                            HotelBranchId = 1,
                            IsDeleted = false,
                            PermissionId = 8,
                            RoleId = 2
                        },
                        new
                        {
                            PermissionAssignmentId = 10,
                            CreatedAt = new DateTime(2024, 4, 14, 17, 59, 4, 290, DateTimeKind.Utc).AddTicks(2104),
                            CreatedBy = "System",
                            HotelBranchId = 1,
                            IsDeleted = false,
                            PermissionId = 8,
                            RoleId = 2
                        },
                        new
                        {
                            PermissionAssignmentId = 11,
                            CreatedAt = new DateTime(2024, 4, 14, 17, 59, 4, 290, DateTimeKind.Utc).AddTicks(2106),
                            CreatedBy = "System",
                            HotelBranchId = 1,
                            IsDeleted = false,
                            PermissionId = 9,
                            RoleId = 2
                        },
                        new
                        {
                            PermissionAssignmentId = 12,
                            CreatedAt = new DateTime(2024, 4, 14, 17, 59, 4, 290, DateTimeKind.Utc).AddTicks(2108),
                            CreatedBy = "System",
                            HotelBranchId = 1,
                            IsDeleted = false,
                            PermissionId = 10,
                            RoleId = 2
                        },
                        new
                        {
                            PermissionAssignmentId = 13,
                            CreatedAt = new DateTime(2024, 4, 14, 17, 59, 4, 290, DateTimeKind.Utc).AddTicks(2110),
                            CreatedBy = "System",
                            HotelBranchId = 1,
                            IsDeleted = false,
                            PermissionId = 11,
                            RoleId = 2
                        },
                        new
                        {
                            PermissionAssignmentId = 14,
                            CreatedAt = new DateTime(2024, 4, 14, 17, 59, 4, 290, DateTimeKind.Utc).AddTicks(2113),
                            CreatedBy = "System",
                            HotelBranchId = 1,
                            IsDeleted = false,
                            PermissionId = 12,
                            RoleId = 2
                        },
                        new
                        {
                            PermissionAssignmentId = 15,
                            CreatedAt = new DateTime(2024, 4, 14, 17, 59, 4, 290, DateTimeKind.Utc).AddTicks(2115),
                            CreatedBy = "System",
                            HotelBranchId = 1,
                            IsDeleted = false,
                            PermissionId = 13,
                            RoleId = 2
                        },
                        new
                        {
                            PermissionAssignmentId = 16,
                            CreatedAt = new DateTime(2024, 4, 14, 17, 59, 4, 290, DateTimeKind.Utc).AddTicks(2117),
                            CreatedBy = "System",
                            HotelBranchId = 1,
                            IsDeleted = false,
                            PermissionId = 14,
                            RoleId = 2
                        },
                        new
                        {
                            PermissionAssignmentId = 17,
                            CreatedAt = new DateTime(2024, 4, 14, 17, 59, 4, 290, DateTimeKind.Utc).AddTicks(2119),
                            CreatedBy = "System",
                            HotelBranchId = 1,
                            IsDeleted = false,
                            PermissionId = 15,
                            RoleId = 2
                        },
                        new
                        {
                            PermissionAssignmentId = 18,
                            CreatedAt = new DateTime(2024, 4, 14, 17, 59, 4, 290, DateTimeKind.Utc).AddTicks(2123),
                            CreatedBy = "System",
                            HotelBranchId = 1,
                            IsDeleted = false,
                            PermissionId = 16,
                            RoleId = 2
                        },
                        new
                        {
                            PermissionAssignmentId = 32,
                            CreatedAt = new DateTime(2024, 4, 14, 17, 59, 4, 290, DateTimeKind.Utc).AddTicks(2124),
                            CreatedBy = "System",
                            HotelBranchId = 1,
                            IsDeleted = false,
                            PermissionId = 18,
                            RoleId = 3
                        },
                        new
                        {
                            PermissionAssignmentId = 19,
                            CreatedAt = new DateTime(2024, 4, 14, 17, 59, 4, 290, DateTimeKind.Utc).AddTicks(2126),
                            CreatedBy = "System",
                            HotelBranchId = 1,
                            IsDeleted = false,
                            PermissionId = 19,
                            RoleId = 3
                        },
                        new
                        {
                            PermissionAssignmentId = 20,
                            CreatedAt = new DateTime(2024, 4, 14, 17, 59, 4, 290, DateTimeKind.Utc).AddTicks(2128),
                            CreatedBy = "System",
                            HotelBranchId = 1,
                            IsDeleted = false,
                            PermissionId = 20,
                            RoleId = 3
                        },
                        new
                        {
                            PermissionAssignmentId = 21,
                            CreatedAt = new DateTime(2024, 4, 14, 17, 59, 4, 290, DateTimeKind.Utc).AddTicks(2130),
                            CreatedBy = "System",
                            HotelBranchId = 1,
                            IsDeleted = false,
                            PermissionId = 21,
                            RoleId = 3
                        },
                        new
                        {
                            PermissionAssignmentId = 22,
                            CreatedAt = new DateTime(2024, 4, 14, 17, 59, 4, 290, DateTimeKind.Utc).AddTicks(2132),
                            CreatedBy = "System",
                            HotelBranchId = 1,
                            IsDeleted = false,
                            PermissionId = 22,
                            RoleId = 3
                        },
                        new
                        {
                            PermissionAssignmentId = 23,
                            CreatedAt = new DateTime(2024, 4, 14, 17, 59, 4, 290, DateTimeKind.Utc).AddTicks(2134),
                            CreatedBy = "System",
                            HotelBranchId = 1,
                            IsDeleted = false,
                            PermissionId = 23,
                            RoleId = 3
                        },
                        new
                        {
                            PermissionAssignmentId = 24,
                            CreatedAt = new DateTime(2024, 4, 14, 17, 59, 4, 290, DateTimeKind.Utc).AddTicks(2975),
                            CreatedBy = "System",
                            HotelBranchId = 1,
                            IsDeleted = false,
                            PermissionId = 24,
                            RoleId = 3
                        },
                        new
                        {
                            PermissionAssignmentId = 25,
                            CreatedAt = new DateTime(2024, 4, 14, 17, 59, 4, 290, DateTimeKind.Utc).AddTicks(2982),
                            CreatedBy = "System",
                            HotelBranchId = 1,
                            IsDeleted = false,
                            PermissionId = 25,
                            RoleId = 3
                        },
                        new
                        {
                            PermissionAssignmentId = 26,
                            CreatedAt = new DateTime(2024, 4, 14, 17, 59, 4, 290, DateTimeKind.Utc).AddTicks(2984),
                            CreatedBy = "System",
                            HotelBranchId = 1,
                            IsDeleted = false,
                            PermissionId = 18,
                            RoleId = 4
                        },
                        new
                        {
                            PermissionAssignmentId = 27,
                            CreatedAt = new DateTime(2024, 4, 14, 17, 59, 4, 290, DateTimeKind.Utc).AddTicks(2987),
                            CreatedBy = "System",
                            HotelBranchId = 1,
                            IsDeleted = false,
                            PermissionId = 19,
                            RoleId = 4
                        },
                        new
                        {
                            PermissionAssignmentId = 28,
                            CreatedAt = new DateTime(2024, 4, 14, 17, 59, 4, 290, DateTimeKind.Utc).AddTicks(2990),
                            CreatedBy = "System",
                            HotelBranchId = 1,
                            IsDeleted = false,
                            PermissionId = 20,
                            RoleId = 4
                        },
                        new
                        {
                            PermissionAssignmentId = 29,
                            CreatedAt = new DateTime(2024, 4, 14, 17, 59, 4, 290, DateTimeKind.Utc).AddTicks(2992),
                            CreatedBy = "System",
                            HotelBranchId = 1,
                            IsDeleted = false,
                            PermissionId = 22,
                            RoleId = 4
                        },
                        new
                        {
                            PermissionAssignmentId = 30,
                            CreatedAt = new DateTime(2024, 4, 14, 17, 59, 4, 290, DateTimeKind.Utc).AddTicks(2994),
                            CreatedBy = "System",
                            HotelBranchId = 1,
                            IsDeleted = false,
                            PermissionId = 24,
                            RoleId = 4
                        },
                        new
                        {
                            PermissionAssignmentId = 31,
                            CreatedAt = new DateTime(2024, 4, 14, 17, 59, 4, 290, DateTimeKind.Utc).AddTicks(2997),
                            CreatedBy = "System",
                            HotelBranchId = 1,
                            IsDeleted = false,
                            PermissionId = 25,
                            RoleId = 4
                        });
                });

            modelBuilder.Entity("HotelManagementSystem.Contracts.Entities.Admin.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<int>("HotelBranchId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            CreatedAt = new DateTime(2024, 4, 14, 17, 59, 4, 290, DateTimeKind.Utc).AddTicks(1658),
                            CreatedBy = "System",
                            Description = "Has all the Permissions",
                            HotelBranchId = 1,
                            IsDeleted = false,
                            Name = "Super Admin",
                            ShortName = "SuperAdmin"
                        },
                        new
                        {
                            RoleId = 2,
                            CreatedAt = new DateTime(2024, 4, 14, 17, 59, 4, 290, DateTimeKind.Utc).AddTicks(1675),
                            CreatedBy = "System",
                            Description = "Has all the root permissions",
                            HotelBranchId = 1,
                            IsDeleted = false,
                            Name = "Admin",
                            ShortName = "Admin"
                        },
                        new
                        {
                            RoleId = 3,
                            CreatedAt = new DateTime(2024, 4, 14, 17, 59, 4, 290, DateTimeKind.Utc).AddTicks(1678),
                            CreatedBy = "System",
                            Description = "Manager of the Front Desk Department",
                            HotelBranchId = 1,
                            IsDeleted = false,
                            Name = "Front Desk Manager",
                            ShortName = "FDManager"
                        },
                        new
                        {
                            RoleId = 4,
                            CreatedAt = new DateTime(2024, 4, 14, 17, 59, 4, 290, DateTimeKind.Utc).AddTicks(1682),
                            CreatedBy = "System",
                            Description = "Assistant staff of the Front Desk Department",
                            HotelBranchId = 1,
                            IsDeleted = false,
                            Name = "Front Desk Assistant",
                            ShortName = "FDAssistant"
                        });
                });

            modelBuilder.Entity("HotelManagementSystem.Contracts.Entities.Admin.RoleAssignment", b =>
                {
                    b.Property<int>("RoleAssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ExpiredAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("HotelBranchId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("RoleAssignmentId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("RoleAssignments");

                    b.HasData(
                        new
                        {
                            RoleAssignmentId = 1,
                            CreatedAt = new DateTime(2024, 4, 14, 17, 59, 4, 290, DateTimeKind.Utc).AddTicks(3366),
                            CreatedBy = "System",
                            HotelBranchId = 1,
                            IsDeleted = false,
                            RoleId = 1,
                            UserId = 5
                        },
                        new
                        {
                            RoleAssignmentId = 2,
                            CreatedAt = new DateTime(2024, 4, 14, 17, 59, 4, 290, DateTimeKind.Utc).AddTicks(3372),
                            CreatedBy = "System",
                            HotelBranchId = 1,
                            IsDeleted = false,
                            RoleId = 3,
                            UserId = 1
                        },
                        new
                        {
                            RoleAssignmentId = 3,
                            CreatedAt = new DateTime(2024, 4, 14, 17, 59, 4, 290, DateTimeKind.Utc).AddTicks(3375),
                            CreatedBy = "System",
                            HotelBranchId = 1,
                            IsDeleted = false,
                            RoleId = 4,
                            UserId = 2
                        },
                        new
                        {
                            RoleAssignmentId = 4,
                            CreatedAt = new DateTime(2024, 4, 14, 17, 59, 4, 290, DateTimeKind.Utc).AddTicks(3378),
                            CreatedBy = "System",
                            HotelBranchId = 1,
                            IsDeleted = false,
                            RoleId = 4,
                            UserId = 3
                        },
                        new
                        {
                            RoleAssignmentId = 5,
                            CreatedAt = new DateTime(2024, 4, 14, 17, 59, 4, 290, DateTimeKind.Utc).AddTicks(3380),
                            CreatedBy = "System",
                            HotelBranchId = 1,
                            IsDeleted = false,
                            RoleId = 3,
                            UserId = 4
                        });
                });

            modelBuilder.Entity("HotelManagementSystem.Contracts.Entities.Admin.Roster", b =>
                {
                    b.Property<int>("RosterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ShiftId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("RosterId");

                    b.HasIndex("ShiftId");

                    b.HasIndex("UserId");

                    b.ToTable("Roster");
                });

            modelBuilder.Entity("HotelManagementSystem.Contracts.Entities.Admin.Shift", b =>
                {
                    b.Property<int>("ShiftId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ShiftName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ShiftId");

                    b.ToTable("Shift");
                });

            modelBuilder.Entity("HotelManagementSystem.Contracts.Entities.Admin.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AddressLine1")
                        .HasColumnType("longtext");

                    b.Property<string>("AddressLine2")
                        .HasColumnType("longtext");

                    b.Property<string>("City")
                        .HasColumnType("longtext");

                    b.Property<string>("Country")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("ExpiredAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Gender")
                        .HasColumnType("longtext");

                    b.Property<Guid>("Guid")
                        .HasColumnType("char(36)");

                    b.Property<int>("HotelBranchId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsExpired")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("State")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Zipcode")
                        .HasColumnType("longtext");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Phone")
                        .IsUnique();

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            CreatedAt = new DateTime(2024, 4, 14, 17, 59, 4, 290, DateTimeKind.Utc).AddTicks(3291),
                            CreatedBy = "System",
                            Email = "namblyakshay@gmail.com",
                            FirstName = "Akshay",
                            Guid = new Guid("a563076f-e2b6-475c-b56f-2bbaacfa89d6"),
                            HotelBranchId = 1,
                            IsActive = true,
                            IsDeleted = false,
                            IsEmailVerified = true,
                            IsExpired = false,
                            LastName = "Nambly",
                            MiddleName = "Mohanan",
                            Password = "Test1234",
                            Phone = "12345",
                            UserName = "akshayn"
                        },
                        new
                        {
                            UserId = 2,
                            CreatedAt = new DateTime(2024, 4, 14, 17, 59, 4, 290, DateTimeKind.Utc).AddTicks(3301),
                            CreatedBy = "System",
                            Email = "chaitraumesh.96@gmail.com",
                            FirstName = "Chaitra",
                            Guid = new Guid("e0fa9e16-0e4e-4af3-8bdb-175d3fe6c405"),
                            HotelBranchId = 1,
                            IsActive = true,
                            IsDeleted = false,
                            IsEmailVerified = true,
                            IsExpired = false,
                            LastName = "Umesh",
                            MiddleName = "",
                            Password = "Test1234",
                            Phone = "123456",
                            UserName = "chaitrau"
                        },
                        new
                        {
                            UserId = 3,
                            CreatedAt = new DateTime(2024, 4, 14, 17, 59, 4, 290, DateTimeKind.Utc).AddTicks(3307),
                            CreatedBy = "System",
                            Email = "jittythomas774@gmail.com",
                            FirstName = "Jitty",
                            Guid = new Guid("3bd3f833-7ca3-4366-8ca1-6e61b8b4a631"),
                            HotelBranchId = 1,
                            IsActive = true,
                            IsDeleted = false,
                            IsEmailVerified = true,
                            IsExpired = false,
                            LastName = "Thomas",
                            MiddleName = "",
                            Password = "Test1234",
                            Phone = "123457",
                            UserName = "jittyt"
                        },
                        new
                        {
                            UserId = 4,
                            CreatedAt = new DateTime(2024, 4, 14, 17, 59, 4, 290, DateTimeKind.Utc).AddTicks(3313),
                            CreatedBy = "System",
                            Email = "robinssojan26@gmail.com",
                            FirstName = "Robins",
                            Guid = new Guid("418a4548-89a2-491a-bc06-6c5c44e99bdd"),
                            HotelBranchId = 1,
                            IsActive = true,
                            IsDeleted = false,
                            IsEmailVerified = true,
                            IsExpired = false,
                            LastName = "Sojan",
                            MiddleName = "",
                            Password = "Test1234",
                            Phone = "123458",
                            UserName = "robinss"
                        },
                        new
                        {
                            UserId = 5,
                            CreatedAt = new DateTime(2024, 4, 14, 17, 59, 4, 290, DateTimeKind.Utc).AddTicks(3318),
                            CreatedBy = "System",
                            Email = "test.admin@gmail.com",
                            FirstName = "Super",
                            Guid = new Guid("6c0f482d-ce4d-4488-808d-017926eda659"),
                            HotelBranchId = 1,
                            IsActive = true,
                            IsDeleted = false,
                            IsEmailVerified = true,
                            IsExpired = false,
                            LastName = "Admin",
                            MiddleName = "",
                            Password = "Test1234",
                            Phone = "123459",
                            UserName = "superAdmin"
                        });
                });

            modelBuilder.Entity("HotelManagementSystem.Contracts.Entities.Admin.UserPasswordResets", b =>
                {
                    b.Property<int>("UserPasswordResetsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ExpiresOn")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsEmailSent")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PasswordResetToken")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("UserPasswordResetsId");

                    b.HasIndex("UserId");

                    b.ToTable("UserPasswordResets");
                });

            modelBuilder.Entity("HotelManagementSystem.Contracts.Entities.Admin.PermissionAssignment", b =>
                {
                    b.HasOne("HotelManagementSystem.Contracts.Entities.Admin.Permission", "Permission")
                        .WithMany("PermissionAssignments")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HotelManagementSystem.Contracts.Entities.Admin.Role", "Role")
                        .WithMany("PermissionAssignments")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("HotelManagementSystem.Contracts.Entities.Admin.RoleAssignment", b =>
                {
                    b.HasOne("HotelManagementSystem.Contracts.Entities.Admin.Role", "Role")
                        .WithMany("RoleAssignments")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HotelManagementSystem.Contracts.Entities.Admin.User", "User")
                        .WithMany("RoleAssignments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HotelManagementSystem.Contracts.Entities.Admin.Roster", b =>
                {
                    b.HasOne("HotelManagementSystem.Contracts.Entities.Admin.Shift", "Shift")
                        .WithMany()
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HotelManagementSystem.Contracts.Entities.Admin.User", "User")
                        .WithMany("Rosters")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shift");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HotelManagementSystem.Contracts.Entities.Admin.UserPasswordResets", b =>
                {
                    b.HasOne("HotelManagementSystem.Contracts.Entities.Admin.User", "User")
                        .WithMany("UserPasswordResets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HotelManagementSystem.Contracts.Entities.Admin.Permission", b =>
                {
                    b.Navigation("PermissionAssignments");
                });

            modelBuilder.Entity("HotelManagementSystem.Contracts.Entities.Admin.Role", b =>
                {
                    b.Navigation("PermissionAssignments");

                    b.Navigation("RoleAssignments");
                });

            modelBuilder.Entity("HotelManagementSystem.Contracts.Entities.Admin.User", b =>
                {
                    b.Navigation("RoleAssignments");

                    b.Navigation("Rosters");

                    b.Navigation("UserPasswordResets");
                });
#pragma warning restore 612, 618
        }
    }
}
