// <auto-generated />
using System;
using HotelManagementSystem.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HotelManagementSystem.Admin.DataAccess.Migrations
{
    [DbContext(typeof(AdminDbContext))]
    [Migration("20240421044713_NewSeedData")]
    partial class NewSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("HotelManagementSystem.Contracts.Entities.Admin.HotelBranch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("IsCurrent")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.HasKey("Id");

                    b.ToTable("Branches");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Dublin 01",
                            City = "Dublin",
                            IsActive = true,
                            IsCurrent = 1,
                            Name = "The Wangchuks Hotel, Dublin"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Cork 01",
                            City = "Cork",
                            IsActive = true,
                            IsCurrent = 0,
                            Name = "The Wangchuks Hotel, Cork"
                        });
                });

            modelBuilder.Entity("HotelManagementSystem.Contracts.Entities.Admin.Permission", b =>
                {
                    b.Property<int>("PermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<int>("HotelBranchId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("PermissionId");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            PermissionId = 1,
                            CreatedAt = new DateTime(2024, 4, 21, 4, 47, 5, 461, DateTimeKind.Utc).AddTicks(8132),
                            Description = "Permission to add a new role to a branch",
                            HotelBranchId = 1,
                            Name = "admin:role:add"
                        },
                        new
                        {
                            PermissionId = 2,
                            CreatedAt = new DateTime(2024, 4, 21, 4, 47, 5, 461, DateTimeKind.Utc).AddTicks(8141),
                            Description = "Permission to view a role",
                            HotelBranchId = 1,
                            Name = "admin:role:view"
                        },
                        new
                        {
                            PermissionId = 3,
                            CreatedAt = new DateTime(2024, 4, 21, 4, 47, 5, 461, DateTimeKind.Utc).AddTicks(8143),
                            Description = "Permission to edit a role",
                            HotelBranchId = 1,
                            Name = "admin:role:edit"
                        },
                        new
                        {
                            PermissionId = 4,
                            CreatedAt = new DateTime(2024, 4, 21, 4, 47, 5, 461, DateTimeKind.Utc).AddTicks(8144),
                            Description = "Permission to delete a role",
                            HotelBranchId = 1,
                            Name = "admin:role:delete"
                        },
                        new
                        {
                            PermissionId = 5,
                            CreatedAt = new DateTime(2024, 4, 21, 4, 47, 5, 461, DateTimeKind.Utc).AddTicks(8146),
                            Description = "Permission to add a permission",
                            HotelBranchId = 1,
                            Name = "admin:permission:add"
                        },
                        new
                        {
                            PermissionId = 6,
                            CreatedAt = new DateTime(2024, 4, 21, 4, 47, 5, 461, DateTimeKind.Utc).AddTicks(8151),
                            Description = "Permission to view a permission",
                            HotelBranchId = 1,
                            Name = "admin:permission:view"
                        },
                        new
                        {
                            PermissionId = 7,
                            CreatedAt = new DateTime(2024, 4, 21, 4, 47, 5, 461, DateTimeKind.Utc).AddTicks(8152),
                            Description = "Permission to edit a permission",
                            HotelBranchId = 1,
                            Name = "admin:permission:edit"
                        },
                        new
                        {
                            PermissionId = 8,
                            CreatedAt = new DateTime(2024, 4, 21, 4, 47, 5, 461, DateTimeKind.Utc).AddTicks(8153),
                            Description = "Permission to delete a permission",
                            HotelBranchId = 1,
                            Name = "admin:permission:delete"
                        },
                        new
                        {
                            PermissionId = 9,
                            CreatedAt = new DateTime(2024, 4, 21, 4, 47, 5, 461, DateTimeKind.Utc).AddTicks(8155),
                            Description = "Permission to add a user",
                            HotelBranchId = 1,
                            Name = "admin:user:add"
                        },
                        new
                        {
                            PermissionId = 10,
                            CreatedAt = new DateTime(2024, 4, 21, 4, 47, 5, 461, DateTimeKind.Utc).AddTicks(8157),
                            Description = "Permission to view a user",
                            HotelBranchId = 1,
                            Name = "admin:user:view"
                        },
                        new
                        {
                            PermissionId = 11,
                            CreatedAt = new DateTime(2024, 4, 21, 4, 47, 5, 461, DateTimeKind.Utc).AddTicks(8158),
                            Description = "Permission to add a user",
                            HotelBranchId = 1,
                            Name = "admin:user:edit"
                        },
                        new
                        {
                            PermissionId = 12,
                            CreatedAt = new DateTime(2024, 4, 21, 4, 47, 5, 461, DateTimeKind.Utc).AddTicks(8159),
                            Description = "Permission to add a user",
                            HotelBranchId = 1,
                            Name = "admin:user:delete"
                        },
                        new
                        {
                            PermissionId = 13,
                            CreatedAt = new DateTime(2024, 4, 21, 4, 47, 5, 461, DateTimeKind.Utc).AddTicks(8161),
                            Description = "Permission to add a visitor",
                            HotelBranchId = 1,
                            Name = "admin:visitor:add"
                        },
                        new
                        {
                            PermissionId = 14,
                            CreatedAt = new DateTime(2024, 4, 21, 4, 47, 5, 461, DateTimeKind.Utc).AddTicks(8162),
                            Description = "Permission to view a visitor",
                            HotelBranchId = 1,
                            Name = "admin:visitor:view"
                        },
                        new
                        {
                            PermissionId = 15,
                            CreatedAt = new DateTime(2024, 4, 21, 4, 47, 5, 461, DateTimeKind.Utc).AddTicks(8163),
                            Description = "Permission to edit a visitor",
                            HotelBranchId = 1,
                            Name = "admin:visitor:edit"
                        },
                        new
                        {
                            PermissionId = 16,
                            CreatedAt = new DateTime(2024, 4, 21, 4, 47, 5, 461, DateTimeKind.Utc).AddTicks(8164),
                            Description = "Permission to delete a visitor",
                            HotelBranchId = 1,
                            Name = "admin:visitor:delete"
                        },
                        new
                        {
                            PermissionId = 17,
                            CreatedAt = new DateTime(2024, 4, 21, 4, 47, 5, 461, DateTimeKind.Utc).AddTicks(8166),
                            Description = "All Permissions",
                            HotelBranchId = 1,
                            Name = "superadmin"
                        },
                        new
                        {
                            PermissionId = 18,
                            CreatedAt = new DateTime(2024, 4, 21, 4, 47, 5, 461, DateTimeKind.Utc).AddTicks(8168),
                            Description = "Permission to add a visitor booking",
                            HotelBranchId = 1,
                            Name = "frontdesk:booking:add"
                        },
                        new
                        {
                            PermissionId = 19,
                            CreatedAt = new DateTime(2024, 4, 21, 4, 47, 5, 461, DateTimeKind.Utc).AddTicks(8169),
                            Description = "Permission to view a visitor booking",
                            HotelBranchId = 1,
                            Name = "frontdesk:booking:view"
                        },
                        new
                        {
                            PermissionId = 20,
                            CreatedAt = new DateTime(2024, 4, 21, 4, 47, 5, 461, DateTimeKind.Utc).AddTicks(8170),
                            Description = "Permission to edit a visitor booking",
                            HotelBranchId = 1,
                            Name = "frontdesk:booking:edit"
                        },
                        new
                        {
                            PermissionId = 21,
                            CreatedAt = new DateTime(2024, 4, 21, 4, 47, 5, 461, DateTimeKind.Utc).AddTicks(8172),
                            Description = "Permission to delete a visitor booking",
                            HotelBranchId = 1,
                            Name = "frontdesk:booking:delete"
                        },
                        new
                        {
                            PermissionId = 22,
                            CreatedAt = new DateTime(2024, 4, 21, 4, 47, 5, 461, DateTimeKind.Utc).AddTicks(8173),
                            Description = "Permission to approve a visitor booking",
                            HotelBranchId = 1,
                            Name = "frontdesk:booking:approve"
                        },
                        new
                        {
                            PermissionId = 23,
                            CreatedAt = new DateTime(2024, 4, 21, 4, 47, 5, 461, DateTimeKind.Utc).AddTicks(8174),
                            Description = "Permission to decline a visitor booking",
                            HotelBranchId = 1,
                            Name = "frontdesk:booking:decline"
                        },
                        new
                        {
                            PermissionId = 24,
                            CreatedAt = new DateTime(2024, 4, 21, 4, 47, 5, 461, DateTimeKind.Utc).AddTicks(8175),
                            Description = "Permission to add a visitor",
                            HotelBranchId = 1,
                            Name = "frontdesk:visitor:add"
                        },
                        new
                        {
                            PermissionId = 25,
                            CreatedAt = new DateTime(2024, 4, 21, 4, 47, 5, 461, DateTimeKind.Utc).AddTicks(8177),
                            Description = "Permission to view a visitor",
                            HotelBranchId = 1,
                            Name = "frontdesk:visitor:view"
                        },
                        new
                        {
                            PermissionId = 26,
                            CreatedAt = new DateTime(2024, 4, 21, 4, 47, 5, 461, DateTimeKind.Utc).AddTicks(8178),
                            Description = "Permission to edit a visitor",
                            HotelBranchId = 1,
                            Name = "frontdesk:visitor:edit"
                        },
                        new
                        {
                            PermissionId = 27,
                            CreatedAt = new DateTime(2024, 4, 21, 4, 47, 5, 461, DateTimeKind.Utc).AddTicks(8179),
                            Description = "Permission to delete a visitor",
                            HotelBranchId = 1,
                            Name = "frontdesk:visitor:delete"
                        },
                        new
                        {
                            PermissionId = 28,
                            CreatedAt = new DateTime(2024, 4, 21, 4, 47, 5, 461, DateTimeKind.Utc).AddTicks(8180),
                            Description = "Permission to Add a room",
                            HotelBranchId = 1,
                            Name = "frontdesk:room:add"
                        },
                        new
                        {
                            PermissionId = 29,
                            CreatedAt = new DateTime(2024, 4, 21, 4, 47, 5, 461, DateTimeKind.Utc).AddTicks(8181),
                            Description = "Permission to View a room",
                            HotelBranchId = 1,
                            Name = "frontdesk:room:view"
                        },
                        new
                        {
                            PermissionId = 30,
                            CreatedAt = new DateTime(2024, 4, 21, 4, 47, 5, 461, DateTimeKind.Utc).AddTicks(8183),
                            Description = "Permission to Edit a room",
                            HotelBranchId = 1,
                            Name = "frontdesk:room:edit"
                        },
                        new
                        {
                            PermissionId = 31,
                            CreatedAt = new DateTime(2024, 4, 21, 4, 47, 5, 461, DateTimeKind.Utc).AddTicks(8184),
                            Description = "Permission to Delete a room",
                            HotelBranchId = 1,
                            Name = "frontdesk:room:delete"
                        },
                        new
                        {
                            PermissionId = 32,
                            CreatedAt = new DateTime(2024, 4, 21, 4, 47, 5, 461, DateTimeKind.Utc).AddTicks(8185),
                            Description = "Permission to Add a room Type",
                            HotelBranchId = 1,
                            Name = "frontdesk:roomType:add"
                        },
                        new
                        {
                            PermissionId = 33,
                            CreatedAt = new DateTime(2024, 4, 21, 4, 47, 5, 461, DateTimeKind.Utc).AddTicks(8186),
                            Description = "Permission to View a room Type",
                            HotelBranchId = 1,
                            Name = "frontdesk:roomType:view"
                        },
                        new
                        {
                            PermissionId = 34,
                            CreatedAt = new DateTime(2024, 4, 21, 4, 47, 5, 461, DateTimeKind.Utc).AddTicks(8232),
                            Description = "Permission to Edit a room Type",
                            HotelBranchId = 1,
                            Name = "frontdesk:roomType:edit"
                        },
                        new
                        {
                            PermissionId = 35,
                            CreatedAt = new DateTime(2024, 4, 21, 4, 47, 5, 461, DateTimeKind.Utc).AddTicks(8233),
                            Description = "Permission to Delete a room Type",
                            HotelBranchId = 1,
                            Name = "frontdesk:roomType:delete"
                        });
                });

            modelBuilder.Entity("HotelManagementSystem.Contracts.Entities.Admin.PermissionAssignment", b =>
                {
                    b.Property<int>("PermissionAssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("longtext");

                    b.Property<int>("HotelBranchId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("PermissionAssignmentId");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId");

                    b.ToTable("PermissionAssignments");

                    b.HasData(
                        new
                        {
                            PermissionAssignmentId = 1,
                            CreatedAt = new DateTime(2024, 4, 21, 4, 47, 5, 461, DateTimeKind.Utc).AddTicks(8329),
                            CreatedBy = "System",
                            HotelBranchId = 1,
                            IsDeleted = false,
                            PermissionId = 17,
                            RoleId = 1
                        },
                        new
                        {
                            PermissionAssignmentId = 2,
                            CreatedAt = new DateTime(2024, 4, 21, 4, 47, 5, 461, DateTimeKind.Utc).AddTicks(8333),
                            CreatedBy = "System",
                            HotelBranchId = 1,
                            IsDeleted = false,
                            PermissionId = 1,
                            RoleId = 2
                        },
                        new
                        {
                            PermissionAssignmentId = 3,
                            CreatedAt = new DateTime(2024, 4, 21, 4, 47, 5, 461, DateTimeKind.Utc).AddTicks(8335),
                            CreatedBy = "System",
                            HotelBranchId = 1,
                            IsDeleted = false,
                            PermissionId = 2,
                            RoleId = 2
                        },
                        new
                        {
                            PermissionAssignmentId = 4,
                            CreatedAt = new DateTime(2024, 4, 21, 4, 47, 5, 461, DateTimeKind.Utc).AddTicks(8336),
                            CreatedBy = "System",
                            HotelBranchId = 1,
                            IsDeleted = false,
                            PermissionId = 3,
                            RoleId = 2
                        },
                        new
                        {
                            PermissionAssignmentId = 5,
                            CreatedAt = new DateTime(2024, 4, 21, 4, 47, 5, 461, DateTimeKind.Utc).AddTicks(8338),
                            CreatedBy = "System",
                            HotelBranchId = 1,
                            IsDeleted = false,
                            PermissionId = 4,
                            RoleId = 2
                        },
                        new
                        {
                            PermissionAssignmentId = 6,
                            CreatedAt = new DateTime(2024, 4, 21, 4, 47, 5, 461, DateTimeKind.Utc).AddTicks(8340),
                            CreatedBy = "System",
                            HotelBranchId = 1,
                            IsDeleted = false,
                            PermissionId = 5,
                            RoleId = 2
                        },
                        new
                        {
                            PermissionAssignmentId = 7,
                            CreatedAt = new DateTime(2024, 4, 21, 4, 47, 5, 461, DateTimeKind.Utc).AddTicks(8342),
                            CreatedBy = "System",
                            HotelBranchId = 1,
                            IsDeleted = false,
                            PermissionId = 6,
                            RoleId = 2
                        },
                        new
                        {
                            PermissionAssignmentId = 8,
                            CreatedAt = new DateTime(2024, 4, 21, 4, 47, 5, 461, DateTimeKind.Utc).AddTicks(8343),
                            CreatedBy = "System",
                            HotelBranchId = 1,
                            IsDeleted = false,
                            PermissionId = 7,
                            RoleId = 2
                        },
                        new
                        {
                            PermissionAssignmentId = 9,
                            CreatedAt = new DateTime(2024, 4, 21, 4, 47, 5, 461, DateTimeKind.Utc).AddTicks(8345),
                            CreatedBy = "System",
                            HotelBranchId = 1,
                            IsDeleted = false,
                            PermissionId = 8,
                            RoleId = 2
                        },
                        new
                        {
                            PermissionAssignmentId = 10,
                            CreatedAt = new DateTime(2024, 4, 21, 4, 47, 5, 461, DateTimeKind.Utc).AddTicks(8347),
                            CreatedBy = "System",
                            HotelBranchId = 1,
                            IsDeleted = false,
                            PermissionId = 8,
                            RoleId = 2
                        },
                        new
                        {
                            PermissionAssignmentId = 11,
                            CreatedAt = new DateTime(2024, 4, 21, 4, 47, 5, 461, DateTimeKind.Utc).AddTicks(8348),
                            CreatedBy = "System",
                            HotelBranchId = 1,
                            IsDeleted = false,
                            PermissionId = 9,
                            RoleId = 2
                        },
                        new
                        {
                            PermissionAssignmentId = 12,
                            CreatedAt = new DateTime(2024, 4, 21, 4, 47, 5, 461, DateTimeKind.Utc).AddTicks(8349),
                            CreatedBy = "System",
                            HotelBranchId = 1,
                            IsDeleted = false,
                            PermissionId = 10,
                            RoleId = 2
                        },
                        new
                        {
                            PermissionAssignmentId = 13,
                            CreatedAt = new DateTime(2024, 4, 21, 4, 47, 5, 461, DateTimeKind.Utc).AddTicks(8351),
                            CreatedBy = "System",
                            HotelBranchId = 1,
                            IsDeleted = false,
                            PermissionId = 11,
                            RoleId = 2
                        },
                        new
                        {
                            PermissionAssignmentId = 14,
                            CreatedAt = new DateTime(2024, 4, 21, 4, 47, 5, 461, DateTimeKind.Utc).AddTicks(8352),
                            CreatedBy = "System",
                            HotelBranchId = 1,
                            IsDeleted = false,
                            PermissionId = 12,
                            RoleId = 2
                        },
                        new
                        {
                            PermissionAssignmentId = 15,
                            CreatedAt = new DateTime(2024, 4, 21, 4, 47, 5, 461, DateTimeKind.Utc).AddTicks(8354),
                            CreatedBy = "System",
                            HotelBranchId = 1,
                            IsDeleted = false,
                            PermissionId = 13,
                            RoleId = 2
                        },
                        new
                        {
                            PermissionAssignmentId = 16,
                            CreatedAt = new DateTime(2024, 4, 21, 4, 47, 5, 461, DateTimeKind.Utc).AddTicks(8355),
                            CreatedBy = "System",
                            HotelBranchId = 1,
                            IsDeleted = false,
                            PermissionId = 14,
                            RoleId = 2
                        },
                        new
                        {
                            PermissionAssignmentId = 17,
                            CreatedAt = new DateTime(2024, 4, 21, 4, 47, 5, 461, DateTimeKind.Utc).AddTicks(8356),
                            CreatedBy = "System",
                            HotelBranchId = 1,
                            IsDeleted = false,
                            PermissionId = 15,
                            RoleId = 2
                        },
                        new
                        {
                            PermissionAssignmentId = 18,
                            CreatedAt = new DateTime(2024, 4, 21, 4, 47, 5, 461, DateTimeKind.Utc).AddTicks(8358),
                            CreatedBy = "System",
                            HotelBranchId = 1,
                            IsDeleted = false,
                            PermissionId = 16,
                            RoleId = 2
                        },
                        new
                        {
                            PermissionAssignmentId = 32,
                            CreatedAt = new DateTime(2024, 4, 21, 4, 47, 5, 461, DateTimeKind.Utc).AddTicks(8360),
                            CreatedBy = "System",
                            HotelBranchId = 1,
                            IsDeleted = false,
                            PermissionId = 18,
                            RoleId = 3
                        },
                        new
                        {
                            PermissionAssignmentId = 19,
                            CreatedAt = new DateTime(2024, 4, 21, 4, 47, 5, 461, DateTimeKind.Utc).AddTicks(8361),
                            CreatedBy = "System",
                            HotelBranchId = 1,
                            IsDeleted = false,
                            PermissionId = 19,
                            RoleId = 3
                        },
                        new
                        {
                            PermissionAssignmentId = 20,
                            CreatedAt = new DateTime(2024, 4, 21, 4, 47, 5, 461, DateTimeKind.Utc).AddTicks(8363),
                            CreatedBy = "System",
                            HotelBranchId = 1,
                            IsDeleted = false,
                            PermissionId = 20,
                            RoleId = 3
                        },
                        new
                        {
                            PermissionAssignmentId = 21,
                            CreatedAt = new DateTime(2024, 4, 21, 4, 47, 5, 461, DateTimeKind.Utc).AddTicks(8364),
                            CreatedBy = "System",
                            HotelBranchId = 1,
                            IsDeleted = false,
                            PermissionId = 21,
                            RoleId = 3
                        },
                        new
                        {
                            PermissionAssignmentId = 22,
                            CreatedAt = new DateTime(2024, 4, 21, 4, 47, 5, 461, DateTimeKind.Utc).AddTicks(8365),
                            CreatedBy = "System",
                            HotelBranchId = 1,
                            IsDeleted = false,
                            PermissionId = 22,
                            RoleId = 3
                        },
                        new
                        {
                            PermissionAssignmentId = 23,
                            CreatedAt = new DateTime(2024, 4, 21, 4, 47, 5, 461, DateTimeKind.Utc).AddTicks(8367),
                            CreatedBy = "System",
                            HotelBranchId = 1,
                            IsDeleted = false,
                            PermissionId = 23,
                            RoleId = 3
                        },
                        new
                        {
                            PermissionAssignmentId = 24,
                            CreatedAt = new DateTime(2024, 4, 21, 4, 47, 5, 461, DateTimeKind.Utc).AddTicks(8368),
                            CreatedBy = "System",
                            HotelBranchId = 1,
                            IsDeleted = false,
                            PermissionId = 24,
                            RoleId = 3
                        },
                        new
                        {
                            PermissionAssignmentId = 25,
                            CreatedAt = new DateTime(2024, 4, 21, 4, 47, 5, 461, DateTimeKind.Utc).AddTicks(8370),
                            CreatedBy = "System",
                            HotelBranchId = 1,
                            IsDeleted = false,
                            PermissionId = 25,
                            RoleId = 3
                        },
                        new
                        {
                            PermissionAssignmentId = 26,
                            CreatedAt = new DateTime(2024, 4, 21, 4, 47, 5, 461, DateTimeKind.Utc).AddTicks(8371),
                            CreatedBy = "System",
                            HotelBranchId = 1,
                            IsDeleted = false,
                            PermissionId = 18,
                            RoleId = 4
                        },
                        new
                        {
                            PermissionAssignmentId = 27,
                            CreatedAt = new DateTime(2024, 4, 21, 4, 47, 5, 461, DateTimeKind.Utc).AddTicks(8372),
                            CreatedBy = "System",
                            HotelBranchId = 1,
                            IsDeleted = false,
                            PermissionId = 19,
                            RoleId = 4
                        },
                        new
                        {
                            PermissionAssignmentId = 28,
                            CreatedAt = new DateTime(2024, 4, 21, 4, 47, 5, 461, DateTimeKind.Utc).AddTicks(8374),
                            CreatedBy = "System",
                            HotelBranchId = 1,
                            IsDeleted = false,
                            PermissionId = 20,
                            RoleId = 4
                        },
                        new
                        {
                            PermissionAssignmentId = 29,
                            CreatedAt = new DateTime(2024, 4, 21, 4, 47, 5, 461, DateTimeKind.Utc).AddTicks(8375),
                            CreatedBy = "System",
                            HotelBranchId = 1,
                            IsDeleted = false,
                            PermissionId = 22,
                            RoleId = 4
                        },
                        new
                        {
                            PermissionAssignmentId = 30,
                            CreatedAt = new DateTime(2024, 4, 21, 4, 47, 5, 461, DateTimeKind.Utc).AddTicks(8376),
                            CreatedBy = "System",
                            HotelBranchId = 1,
                            IsDeleted = false,
                            PermissionId = 24,
                            RoleId = 4
                        },
                        new
                        {
                            PermissionAssignmentId = 31,
                            CreatedAt = new DateTime(2024, 4, 21, 4, 47, 5, 461, DateTimeKind.Utc).AddTicks(8378),
                            CreatedBy = "System",
                            HotelBranchId = 1,
                            IsDeleted = false,
                            PermissionId = 25,
                            RoleId = 4
                        },
                        new
                        {
                            PermissionAssignmentId = 40,
                            CreatedAt = new DateTime(2024, 4, 21, 4, 47, 5, 461, DateTimeKind.Utc).AddTicks(8382),
                            CreatedBy = "System",
                            HotelBranchId = 1,
                            IsDeleted = false,
                            PermissionId = 28,
                            RoleId = 3
                        },
                        new
                        {
                            PermissionAssignmentId = 33,
                            CreatedAt = new DateTime(2024, 4, 21, 4, 47, 5, 461, DateTimeKind.Utc).AddTicks(8385),
                            CreatedBy = "System",
                            HotelBranchId = 1,
                            IsDeleted = false,
                            PermissionId = 29,
                            RoleId = 3
                        },
                        new
                        {
                            PermissionAssignmentId = 34,
                            CreatedAt = new DateTime(2024, 4, 21, 4, 47, 5, 461, DateTimeKind.Utc).AddTicks(8386),
                            CreatedBy = "System",
                            HotelBranchId = 1,
                            IsDeleted = false,
                            PermissionId = 30,
                            RoleId = 3
                        },
                        new
                        {
                            PermissionAssignmentId = 35,
                            CreatedAt = new DateTime(2024, 4, 21, 4, 47, 5, 461, DateTimeKind.Utc).AddTicks(8387),
                            CreatedBy = "System",
                            HotelBranchId = 1,
                            IsDeleted = false,
                            PermissionId = 31,
                            RoleId = 3
                        },
                        new
                        {
                            PermissionAssignmentId = 36,
                            CreatedAt = new DateTime(2024, 4, 21, 4, 47, 5, 461, DateTimeKind.Utc).AddTicks(8389),
                            CreatedBy = "System",
                            HotelBranchId = 1,
                            IsDeleted = false,
                            PermissionId = 32,
                            RoleId = 3
                        },
                        new
                        {
                            PermissionAssignmentId = 37,
                            CreatedAt = new DateTime(2024, 4, 21, 4, 47, 5, 461, DateTimeKind.Utc).AddTicks(8390),
                            CreatedBy = "System",
                            HotelBranchId = 1,
                            IsDeleted = false,
                            PermissionId = 33,
                            RoleId = 3
                        },
                        new
                        {
                            PermissionAssignmentId = 38,
                            CreatedAt = new DateTime(2024, 4, 21, 4, 47, 5, 461, DateTimeKind.Utc).AddTicks(8391),
                            CreatedBy = "System",
                            HotelBranchId = 1,
                            IsDeleted = false,
                            PermissionId = 34,
                            RoleId = 3
                        },
                        new
                        {
                            PermissionAssignmentId = 39,
                            CreatedAt = new DateTime(2024, 4, 21, 4, 47, 5, 461, DateTimeKind.Utc).AddTicks(8393),
                            CreatedBy = "System",
                            HotelBranchId = 1,
                            IsDeleted = false,
                            PermissionId = 35,
                            RoleId = 3
                        });
                });

            modelBuilder.Entity("HotelManagementSystem.Contracts.Entities.Admin.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<int>("HotelBranchId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            CreatedAt = new DateTime(2024, 4, 21, 4, 47, 5, 461, DateTimeKind.Utc).AddTicks(8083),
                            CreatedBy = "System",
                            Description = "Has all the Permissions",
                            HotelBranchId = 1,
                            IsDeleted = false,
                            Name = "Super Admin",
                            ShortName = "SuperAdmin"
                        },
                        new
                        {
                            RoleId = 2,
                            CreatedAt = new DateTime(2024, 4, 21, 4, 47, 5, 461, DateTimeKind.Utc).AddTicks(8092),
                            CreatedBy = "System",
                            Description = "Has all the root permissions",
                            HotelBranchId = 1,
                            IsDeleted = false,
                            Name = "Admin",
                            ShortName = "Admin"
                        },
                        new
                        {
                            RoleId = 3,
                            CreatedAt = new DateTime(2024, 4, 21, 4, 47, 5, 461, DateTimeKind.Utc).AddTicks(8094),
                            CreatedBy = "System",
                            Description = "Manager of the Front Desk Department",
                            HotelBranchId = 1,
                            IsDeleted = false,
                            Name = "Front Desk Manager",
                            ShortName = "FDManager"
                        },
                        new
                        {
                            RoleId = 4,
                            CreatedAt = new DateTime(2024, 4, 21, 4, 47, 5, 461, DateTimeKind.Utc).AddTicks(8096),
                            CreatedBy = "System",
                            Description = "Assistant staff of the Front Desk Department",
                            HotelBranchId = 1,
                            IsDeleted = false,
                            Name = "Front Desk Assistant",
                            ShortName = "FDAssistant"
                        });
                });

            modelBuilder.Entity("HotelManagementSystem.Contracts.Entities.Admin.RoleAssignment", b =>
                {
                    b.Property<int>("RoleAssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ExpiredAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("HotelBranchId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("RoleAssignmentId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("RoleAssignments");

                    b.HasData(
                        new
                        {
                            RoleAssignmentId = 1,
                            CreatedAt = new DateTime(2024, 4, 21, 4, 47, 5, 461, DateTimeKind.Utc).AddTicks(8597),
                            CreatedBy = "System",
                            HotelBranchId = 1,
                            IsDeleted = false,
                            RoleId = 1,
                            UserId = 5
                        },
                        new
                        {
                            RoleAssignmentId = 2,
                            CreatedAt = new DateTime(2024, 4, 21, 4, 47, 5, 461, DateTimeKind.Utc).AddTicks(8602),
                            CreatedBy = "System",
                            HotelBranchId = 1,
                            IsDeleted = false,
                            RoleId = 3,
                            UserId = 1
                        },
                        new
                        {
                            RoleAssignmentId = 3,
                            CreatedAt = new DateTime(2024, 4, 21, 4, 47, 5, 461, DateTimeKind.Utc).AddTicks(8604),
                            CreatedBy = "System",
                            HotelBranchId = 1,
                            IsDeleted = false,
                            RoleId = 4,
                            UserId = 2
                        },
                        new
                        {
                            RoleAssignmentId = 4,
                            CreatedAt = new DateTime(2024, 4, 21, 4, 47, 5, 461, DateTimeKind.Utc).AddTicks(8605),
                            CreatedBy = "System",
                            HotelBranchId = 1,
                            IsDeleted = false,
                            RoleId = 4,
                            UserId = 3
                        },
                        new
                        {
                            RoleAssignmentId = 5,
                            CreatedAt = new DateTime(2024, 4, 21, 4, 47, 5, 461, DateTimeKind.Utc).AddTicks(8607),
                            CreatedBy = "System",
                            HotelBranchId = 1,
                            IsDeleted = false,
                            RoleId = 3,
                            UserId = 4
                        });
                });

            modelBuilder.Entity("HotelManagementSystem.Contracts.Entities.Admin.Roster", b =>
                {
                    b.Property<int>("RosterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ShiftId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("RosterId");

                    b.HasIndex("ShiftId");

                    b.HasIndex("UserId");

                    b.ToTable("Roster");
                });

            modelBuilder.Entity("HotelManagementSystem.Contracts.Entities.Admin.Shift", b =>
                {
                    b.Property<int>("ShiftId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ShiftName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ShiftId");

                    b.ToTable("Shift");
                });

            modelBuilder.Entity("HotelManagementSystem.Contracts.Entities.Admin.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AddressLine1")
                        .HasColumnType("longtext");

                    b.Property<string>("AddressLine2")
                        .HasColumnType("longtext");

                    b.Property<string>("City")
                        .HasColumnType("longtext");

                    b.Property<string>("Country")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("ExpiredAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Gender")
                        .HasColumnType("longtext");

                    b.Property<Guid>("Guid")
                        .HasColumnType("char(36)");

                    b.Property<int>("HotelBranchId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsExpired")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("State")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Zipcode")
                        .HasColumnType("longtext");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Phone")
                        .IsUnique();

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            CreatedAt = new DateTime(2024, 4, 21, 4, 47, 5, 461, DateTimeKind.Utc).AddTicks(8537),
                            CreatedBy = "System",
                            Email = "namblyakshay@gmail.com",
                            FirstName = "Akshay",
                            Guid = new Guid("e324fe3d-daf0-4961-9af3-95ddaa4e367e"),
                            HotelBranchId = 1,
                            IsActive = true,
                            IsDeleted = false,
                            IsEmailVerified = true,
                            IsExpired = false,
                            LastName = "Nambly",
                            MiddleName = "Mohanan",
                            Password = "Test1234",
                            Phone = "12345",
                            UserName = "akshayn"
                        },
                        new
                        {
                            UserId = 2,
                            CreatedAt = new DateTime(2024, 4, 21, 4, 47, 5, 461, DateTimeKind.Utc).AddTicks(8546),
                            CreatedBy = "System",
                            Email = "chaitraumesh.96@gmail.com",
                            FirstName = "Chaitra",
                            Guid = new Guid("b1bff33a-7056-44e0-a493-5c05ef669203"),
                            HotelBranchId = 1,
                            IsActive = true,
                            IsDeleted = false,
                            IsEmailVerified = true,
                            IsExpired = false,
                            LastName = "Umesh",
                            MiddleName = "",
                            Password = "Test1234",
                            Phone = "123456",
                            UserName = "chaitrau"
                        },
                        new
                        {
                            UserId = 3,
                            CreatedAt = new DateTime(2024, 4, 21, 4, 47, 5, 461, DateTimeKind.Utc).AddTicks(8549),
                            CreatedBy = "System",
                            Email = "jittythomas774@gmail.com",
                            FirstName = "Jitty",
                            Guid = new Guid("b246b19d-3521-4252-b0a7-44c60feb588f"),
                            HotelBranchId = 1,
                            IsActive = true,
                            IsDeleted = false,
                            IsEmailVerified = true,
                            IsExpired = false,
                            LastName = "Thomas",
                            MiddleName = "",
                            Password = "Test1234",
                            Phone = "123457",
                            UserName = "jittyt"
                        },
                        new
                        {
                            UserId = 4,
                            CreatedAt = new DateTime(2024, 4, 21, 4, 47, 5, 461, DateTimeKind.Utc).AddTicks(8553),
                            CreatedBy = "System",
                            Email = "robinssojan26@gmail.com",
                            FirstName = "Robins",
                            Guid = new Guid("562e2442-c444-4f0f-b482-d6108df2dc92"),
                            HotelBranchId = 1,
                            IsActive = true,
                            IsDeleted = false,
                            IsEmailVerified = true,
                            IsExpired = false,
                            LastName = "Sojan",
                            MiddleName = "",
                            Password = "Test1234",
                            Phone = "123458",
                            UserName = "robinss"
                        },
                        new
                        {
                            UserId = 5,
                            CreatedAt = new DateTime(2024, 4, 21, 4, 47, 5, 461, DateTimeKind.Utc).AddTicks(8556),
                            CreatedBy = "System",
                            Email = "test.admin@gmail.com",
                            FirstName = "Super",
                            Guid = new Guid("6f33cfa5-7de7-4c4b-a332-366bf575073d"),
                            HotelBranchId = 1,
                            IsActive = true,
                            IsDeleted = false,
                            IsEmailVerified = true,
                            IsExpired = false,
                            LastName = "Admin",
                            MiddleName = "",
                            Password = "Test1234",
                            Phone = "123459",
                            UserName = "superAdmin"
                        });
                });

            modelBuilder.Entity("HotelManagementSystem.Contracts.Entities.Admin.UserPasswordResets", b =>
                {
                    b.Property<int>("UserPasswordResetsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ExpiresOn")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsEmailSent")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PasswordResetToken")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("UserPasswordResetsId");

                    b.HasIndex("UserId");

                    b.ToTable("UserPasswordResets");
                });

            modelBuilder.Entity("HotelManagementSystem.Contracts.Entities.Admin.PermissionAssignment", b =>
                {
                    b.HasOne("HotelManagementSystem.Contracts.Entities.Admin.Permission", "Permission")
                        .WithMany("PermissionAssignments")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HotelManagementSystem.Contracts.Entities.Admin.Role", "Role")
                        .WithMany("PermissionAssignments")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("HotelManagementSystem.Contracts.Entities.Admin.RoleAssignment", b =>
                {
                    b.HasOne("HotelManagementSystem.Contracts.Entities.Admin.Role", "Role")
                        .WithMany("RoleAssignments")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HotelManagementSystem.Contracts.Entities.Admin.User", "User")
                        .WithMany("RoleAssignments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HotelManagementSystem.Contracts.Entities.Admin.Roster", b =>
                {
                    b.HasOne("HotelManagementSystem.Contracts.Entities.Admin.Shift", "Shift")
                        .WithMany()
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HotelManagementSystem.Contracts.Entities.Admin.User", "User")
                        .WithMany("Rosters")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shift");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HotelManagementSystem.Contracts.Entities.Admin.UserPasswordResets", b =>
                {
                    b.HasOne("HotelManagementSystem.Contracts.Entities.Admin.User", "User")
                        .WithMany("UserPasswordResets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HotelManagementSystem.Contracts.Entities.Admin.Permission", b =>
                {
                    b.Navigation("PermissionAssignments");
                });

            modelBuilder.Entity("HotelManagementSystem.Contracts.Entities.Admin.Role", b =>
                {
                    b.Navigation("PermissionAssignments");

                    b.Navigation("RoleAssignments");
                });

            modelBuilder.Entity("HotelManagementSystem.Contracts.Entities.Admin.User", b =>
                {
                    b.Navigation("RoleAssignments");

                    b.Navigation("Rosters");

                    b.Navigation("UserPasswordResets");
                });
#pragma warning restore 612, 618
        }
    }
}
